# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/LAB2D_Timer/LAB2D_Timer.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB2D_Timer || ORIG_REF_NAME==LAB2D_Timer} -quiet] -quiet

# IP: bd/LAB2D_Timer/ip/LAB2D_Timer_processing_system7_0_0/LAB2D_Timer_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB2D_Timer_processing_system7_0_0 || ORIG_REF_NAME==LAB2D_Timer_processing_system7_0_0} -quiet] -quiet

# IP: bd/LAB2D_Timer/ip/LAB2D_Timer_axi_gpio_0_0/LAB2D_Timer_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB2D_Timer_axi_gpio_0_0 || ORIG_REF_NAME==LAB2D_Timer_axi_gpio_0_0} -quiet] -quiet

# IP: bd/LAB2D_Timer/ip/LAB2D_Timer_axi_gpio_1_0/LAB2D_Timer_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB2D_Timer_axi_gpio_1_0 || ORIG_REF_NAME==LAB2D_Timer_axi_gpio_1_0} -quiet] -quiet

# IP: bd/LAB2D_Timer/ip/LAB2D_Timer_axi_smc_0/LAB2D_Timer_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB2D_Timer_axi_smc_0 || ORIG_REF_NAME==LAB2D_Timer_axi_smc_0} -quiet] -quiet

# IP: bd/LAB2D_Timer/ip/LAB2D_Timer_rst_ps7_0_50M_0/LAB2D_Timer_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB2D_Timer_rst_ps7_0_50M_0 || ORIG_REF_NAME==LAB2D_Timer_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/LAB2D_Timer/ip/LAB2D_Timer_axi_timer_0_0/LAB2D_Timer_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB2D_Timer_axi_timer_0_0 || ORIG_REF_NAME==LAB2D_Timer_axi_timer_0_0} -quiet] -quiet

# IP: bd/LAB2D_Timer/ip/LAB2D_Timer_xlconcat_0_0/LAB2D_Timer_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LAB2D_Timer_xlconcat_0_0 || ORIG_REF_NAME==LAB2D_Timer_xlconcat_0_0} -quiet] -quiet

# XDC: d:/Vivado_Project/LAB2D/LAB2D.gen/sources_1/bd/LAB2D_Timer/LAB2D_Timer_ooc.xdc
