# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Documents/Hoc_hanh/Vivado_Project/LAB2/LAB2.srcs/sources_1/bd/zybo_lab2/ip/zybo_lab2_processing_system7_0_0/zybo_lab2_processing_system7_0_0.xci
# IP: The module: 'zybo_lab2_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Hoc_hanh/Vivado_Project/LAB2/LAB2.gen/sources_1/bd/zybo_lab2/ip/zybo_lab2_processing_system7_0_0/zybo_lab2_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_lab2_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Documents/Hoc_hanh/Vivado_Project/LAB2/LAB2.srcs/sources_1/bd/zybo_lab2/ip/zybo_lab2_processing_system7_0_0/zybo_lab2_processing_system7_0_0.xci
# IP: The module: 'zybo_lab2_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Hoc_hanh/Vivado_Project/LAB2/LAB2.gen/sources_1/bd/zybo_lab2/ip/zybo_lab2_processing_system7_0_0/zybo_lab2_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_lab2_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
