# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo_lab2/zybo_lab2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_lab2 || ORIG_REF_NAME==zybo_lab2} -quiet] -quiet

# IP: bd/zybo_lab2/ip/zybo_lab2_processing_system7_0_0/zybo_lab2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_lab2_processing_system7_0_0 || ORIG_REF_NAME==zybo_lab2_processing_system7_0_0} -quiet] -quiet

# IP: bd/zybo_lab2/ip/zybo_lab2_axi_gpio_0_0/zybo_lab2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_lab2_axi_gpio_0_0 || ORIG_REF_NAME==zybo_lab2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zybo_lab2/ip/zybo_lab2_axi_smc_0/zybo_lab2_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_lab2_axi_smc_0 || ORIG_REF_NAME==zybo_lab2_axi_smc_0} -quiet] -quiet

# IP: bd/zybo_lab2/ip/zybo_lab2_rst_ps7_0_50M_0/zybo_lab2_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_lab2_rst_ps7_0_50M_0 || ORIG_REF_NAME==zybo_lab2_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zybo_lab2/ip/zybo_lab2_axi_gpio_1_0/zybo_lab2_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_lab2_axi_gpio_1_0 || ORIG_REF_NAME==zybo_lab2_axi_gpio_1_0} -quiet] -quiet

# XDC: d:/Vivado_Project/LAB2/LAB2.gen/sources_1/bd/zybo_lab2/zybo_lab2_ooc.xdc
